meta_product_name: "1953"
meta_title: "1953 | Share Your Stories"
meta_description: "Trade books and connect with readers around you."
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`